version: '3'
services: 
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes: 
      - /app/node_modules
      - ./frontend:/app
# api: 
#   build; ./app
#   ports:
#     - 5050:5050